image: node:20

definitions:
  steps:
    - step: &build-test
        name: Build and Test
        caches:
          - node
        script:
          - npm install
          - npm test

    - step: &deploy-staging
        name: Deploy to Staging
        deployment: staging
        script:
          - pipe: atlassian/aws-ecs-deploy:1.0.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              CLUSTER_NAME: 'mobilemar-cluster'
              SERVICE_NAME: 'mobilemar-service'
              TASK_DEFINITION: 'taskDefinition.json'

    - step: &deploy-production
        name: Deploy to Production
        deployment: production
        trigger: manual
        script:
          - echo "Deploying to Production environment"

pipelines:
  default:
    - step: *build-test
    - step: *deploy-staging
  branches:
    prod:
      - step: *build-test
      - step: *deploy-production

