image: node:20

definitions:
  steps:
    - step: &build-test
        name: Build and Test
        caches:
          - node
        script:
          - npm install
          - npm test

    - step: &deploy-staging
        name: Deploy to Staging
        deployment: staging
        script:
          - echo "Deploying to Staging environment"
          
    - step: &deploy-production
        name: Deploy to Production
        deployment: production
        trigger: manual
        script:
          - echo "Deploying to Production environment"

pipelines:
  default:
    - step: *build-test
    - step: *deploy-staging
    - step: *deploy-production

